

insert into user (id, account_expired, account_locked, credentials_expired, username, account_enabled, password) VALUES (1, 0, 0, 0, 'test', 1, 'test');
insert into role (id, name) VALUES (1, 'ADMIN');
insert into user_roles (user_id, roles_id) VALUES (1, 1);


--create table role (id bigint generated by default as identity (start with 1), 
  --name varchar(255), primary key (id))
--create table user (id bigint generated by default as identity (start with 1), account_expired boolean, account_locked boolean, credentials_expired boolean, account_enabled boolean, password varchar(255), username varchar(255) not null, primary key (id))
--create table user_roles (user_id bigint not null, roles_id bigint not null, primary key (user_id, roles_id))
